name: Copy Secrets by Environment

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger this workflow

jobs:
  copy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      # Add any necessary setup steps here, such as installing required dependencies

      - name: Retrieve and copy secrets by environment
        run: |
          # Define the list of environments
          environments=("development" "staging" "production")
          
          # Loop through each environment
          for env in "${environments[@]}"; do
            echo "Checking if environment $env exists..."
            
            # Check if the environment exists in the destination repository
            response=$(curl --location --request GET \
              "https://api.github.com/repos/neeratikrishna15/dev-environment/environments/$env" \
              --header "Authorization: Bearer ${{ secrets.TOKEN }}")
            
            if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
              echo "Environment $env does not exist. Creating it..."
              
              # Create the environment in the destination repository
              curl --location --request POST \
                "https://api.github.com/repos/neeratikrishna15/dev-environment/environments" \
                --header "Authorization: Bearer ${{ secrets.TOKEN }}" \
                --header 'Content-Type: application/json' \
                --data-raw "{\"name\":\"$env\"}"
            fi
            
            # Retrieve the list of secrets for the current environment in the source repository
            secrets=$(curl --location --request GET \
              "https://api.github.com/repos/neeratikrishna15/databricksencryption/actions/secrets?environment=$env" \
              --header "Authorization: Bearer ${{ secrets.TOKEN }}" | jq -r '.secrets[].name')
            
            # Loop through each secret and copy it to the corresponding environment in the destination repository
            for secret_name in $secrets; do
              echo "Copying secret $secret_name to environment $env..."
              
              # Retrieve the value of the secret
              secret_value=$(curl --location --request GET \
                "https://api.github.com/repos/neeratikrishna15/databricksencryption/actions/secrets/$secret_name" \
                --header "Authorization: Bearer ${{ secrets.TOKEN }}" | jq -r '.encrypted_value')
              
              # Create or update the secret in the destination repository
              curl --location --request PUT \
                "https://api.github.com/repos/neeratikrishna15/dev-environment/actions/secrets/$secret_name" \
                --header "Authorization: Bearer ${{ secrets.TOKEN }}" \
                --header 'Content-Type: application/json' \
                --data-raw "{\"encrypted_value\":\"$secret_value\",\"key_id\":\"3380204578043523366\"}"
            done
          done
