name: Sync Secrets 22

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger this workflow

jobs:
  sync-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync Secrets
        
        run: |
            curl --location --request GET 'https://api.github.com/repos/neeratikrishna15/databricksencryption/actions/secrets' --header 'Authorization: Bearer ${{ secrets.TOKEN }}'
