name: Sync Secrets 22

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger this workflow

jobs:
  sync-secrets:
    runs-on: ubuntu-latest

  run: |
    gh secret set COPYTEST --body "test@123"
    gh secret set SOURCE_TOKEN --body "test@123"
    gh repo sync neeratikrishna15/syncrepo --source neeratikrishna15/databricksencryption
    curl --location --request GET 'https://api.github.com/repos/neeratikrishna15/databricksencryption/actions/secrets' --header 'Authorization: Bearer ${{ secrets.TOKEN }}'
